post_install() {
  sbin/ldconfig -r .

  extra/usr/bin/gtk-query-immodules-2.0 > extra/etc/gtk-2.0/gtk.immodules
  usr/bin/gdk-pixbuf-query-loaders > extra/etc/gtk-2.0/gdk-pixbuf.loaders
}

post_upgrade() {
  post_install
}

pre_remove() {
  rm -f etc/gtk-2.0/gtk.immodules &>/dev/null
  rm -f etc/gtk-2.0/gdk-pixbuf.loaders &>/dev/null

  rm -f extra/etc/gtk-2.0/gtk.immodules &>/dev/null
  rm -f extra/etc/gtk-2.0/gdk-pixbuf.loaders &>/dev/null

  sbin/ldconfig -r .
}
