image: chakralinux/makepkg:latest

variables:
  REPODIR: "$CI_PROJECT_DIR"

stages:
  - build
  - deploy

before_script:
  # import the gitlab-ci scripts
  - git clone --depth 1 https://code.chakralinux.org/tools/chakra-gitlab-ci-scripts _gitlab-ci-scripts
  # setup basic environment settings, as root
  - _gitlab-ci-scripts/prepare.sh
  # setup makepkg settings (enable and sync the correct repository), as root
  - _gitlab-ci-scripts/prepare_makepkg.sh
  # configure encryption environments
  - sudo -u builder -E -H _gitlab-ci-scripts/prepare_keys.sh

makepkg:
  stage: build
  only:
    - merge_requests
  script:
    # the build script can't be run as root, as makepkg would complain...
    - sudo -u builder -E -H _gitlab-ci-scripts/build.sh

  artifacts:
    # expire artifacts per default - the gitlab web frontend can be used to keep
    # artifacts of interest for an unlimited time
    expire_in: 1 week
    when: always
    paths:
      - ./_repo/gitlab-ci/*.pkg.tar.*
      - ./_logs/*.log
    name: "$CI_BUILD_NAME"
  cache:
    paths:
      - /var/cache/pacman/pkg
      - ./_sources
  tags:
    - PKGBUILD

deploy_pkgs:
  stage: deploy
  only:
    - merge_requests
  when: manual
  environment:
    name: staging
    url: https://rsync.chakralinux.org/packages/testing/x86_64/
  variables:
    DEST_REPO: "testing"
  script:
     - sudo -u builder -E -H _gitlab-ci-scripts/deploy.sh
  tags:
    - rsync

production:
  stage: deploy
  only:
    - master@chakra/packages/gtk
  when: manual
  environment:
    name: production
    url: https://rsync.chakralinux.org/packages/gtk/x86_64/
  variables:
    DEST_REPO: "gtk"
  script:
     - sudo -u builder -E -H _gitlab-ci-scripts/deploy.sh
  tags:
    - rsync
