image: chakralinux/makepkg:latest

variables:
  REPODIR: "$CI_PROJECT_DIR"

stages:
  - build
  - deploy

before_script:
  # import the gitlab-ci scripts
  - git clone --depth 1 https://code.chakralinux.org/tools/chakra-gitlab-ci-scripts _gitlab-ci-scripts
  # setup basic environment settings, as root
  - _gitlab-ci-scripts/prepare.sh
  # import pgp keys flagged as valid
  - sudo -u builder -E -H _gitlab-ci-scripts/import-validpgpkeys.sh

makepkg:
  stage: build
  only:
    - merge_requests
  script:
    # setup makepkg settings (enable and sync the correct repository), as root
    - _gitlab-ci-scripts/prepare_makepkg.sh
    # the build script can't be run as root, as makepkg would complain...
    - sudo -u builder -E -H _gitlab-ci-scripts/build.sh

  artifacts:
    # expire artifacts per default - the gitlab web frontend can be used to keep
    # artifacts of interest for an unlimited time
    expire_in: 1 week
    paths:
      - ./_repo/gitlab-ci/*.pkg.tar.*
      - ./_logs/*.log
    name: "$CI_BUILD_NAME"
  cache:
    paths:
      - /var/cache/pacman/pkg
      - ./_sources
  tags:
    - PKGBUILD

staging:
  stage: deploy
  only:
    - merge_requests
  when: manual
  environment:
    name: staging
    url: https://rsync.chakralinux.org/packages/testing/x86_64/
  variables:
    DEPLOY_SERVER: "$DEPLOY_SERVER"
    SSH_USER: "$SSH_USER"
    SSH_PORT: "$SSH_PORT"
    GPG_PASSWORD: "$GPG_PASSWORD"
    DEST_REPO: "testing"
  tags:
    - rsync
  script:
     - _gitlab-ci-scripts/deploy.sh

production:
  stage: deploy
  only:
    - master@chakra/packages/core
  when: manual
  environment:
    name: production
    url: https://rsync.chakralinux.org/packages/core/x86_64/
  variables:
    DEPLOY_SERVER: "$DEPLOY_SERVER"
    SSH_USER: "$SSH_USER"
    SSH_PORT: "$SSH_PORT"
    GPG_PASSWORD: "$GPG_PASSWORD"
    DEST_REPO: "core"
  tags:
    - rsync
  script:
     - _gitlab-ci-scripts/deploy.sh
