post_install() {
    sbin/ldconfig -r .

    extra/usr/bin/gtk-query-immodules-3.0 --update-cache &>/dev/null
    usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas &>/dev/null
}

post_upgrade() {
    post_install
}

pre_remove() {
    rm -f usr/lib/gtk-3.0/3.0.0/immodules.cache &>/dev/null
    rm -f extra/usr/lib/gtk-3.0/3.0.0/immodules.cache &>/dev/null
}
post_remove() {
    sbin/ldconfig -r .

    usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas &>/dev/null
}
